"use client";

import { useEffect, useState } from "react";
import { AIAnalysisResponse } from "@/types/ai";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Sparkles, TrendingUp, AlertTriangle, ArrowRight, RefreshCw, CheckCircle2, Zap } from "lucide-react";
import { cn } from "@/lib/utils";

export function AiAnalysisPanel() {
  const [analysis, setAnalysis] = useState<AIAnalysisResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchInsights = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/ai/insights", { cache: "no-store" });
      if (!res.ok) throw new Error("Failed to fetch AI insights");
      const data = await res.json();
      setAnalysis(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  if (loading) {
    return <AiLoadingState />;
  }

  if (error || !analysis) {
    return (
      <Card className="flex flex-col items-center justify-center min-h-[400px] border-rose-500/20 bg-rose-500/5">
        <AlertTriangle className="h-10 w-10 text-rose-500 mb-4" />
        <p className="text-sm text-rose-600 font-medium">Unable to connect to Nexus AI Engine.</p>
        <button onClick={fetchInsights} className="mt-4 px-4 py-2 border rounded-md text-xs hover:bg-rose-500/10">
          Try Again
        </button>
      </Card>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      {/* Executive Summary */}
      <Card className="relative overflow-hidden border-indigo-500/30 shadow-md bg-gradient-to-br from-indigo-500/10 via-background to-background">
        <div className="absolute top-0 right-0 p-6 opacity-10">
          <Sparkles className="h-32 w-32 text-indigo-500" />
        </div>
        <CardHeader className="pb-3 border-b border-indigo-500/10">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-2 rounded-lg bg-indigo-500/20 text-indigo-600 dark:text-indigo-400">
                <Zap className="h-5 w-5" />
              </div>
              <div>
                <CardTitle className="text-lg">Executive AI Summary</CardTitle>
                <CardDescription>Generated by Nexus Intelligence</CardDescription>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className={cn("text-xs font-semibold px-2.5 py-1 rounded-full border", 
                analysis.priority === "Critical" ? "bg-rose-500/20 text-rose-600 border-rose-500/30" : 
                analysis.priority === "High" ? "bg-orange-500/20 text-orange-600 border-orange-500/30" : 
                "bg-emerald-500/20 text-emerald-600 border-emerald-500/30")}>
                {analysis.priority} Priority
              </div>
              <button onClick={fetchInsights} className="p-2 hover:bg-indigo-500/10 rounded-full transition-colors group">
                <RefreshCw className="h-4 w-4 text-indigo-500 group-active:animate-spin" />
              </button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="pt-4">
          <p className="text-sm leading-relaxed text-foreground/90 font-medium">
            {analysis.summary}
          </p>
          <div className="mt-4 flex items-center gap-4 text-xs font-medium text-muted-foreground">
            <div className="flex items-center gap-1.5">
              <CheckCircle2 className="h-4 w-4 text-emerald-500" />
              Confidence: {analysis.confidenceScore}%
            </div>
            <div className="flex items-center gap-1.5">
              <TrendingUp className={cn("h-4 w-4", analysis.trendDirection === "Up" ? "text-emerald-500" : "text-rose-500")} />
              Trend: {analysis.trendDirection}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Opportunities & Risks Grid */}
      <div className="grid gap-4 flex-1">
        {analysis.opportunities.map((opp, idx) => (
          <Card key={idx} className="border-emerald-500/20 bg-emerald-500/5 dark:bg-emerald-500/10 shadow-sm transition-all hover:shadow-md">
            <CardContent className="p-4 flex gap-4">
              <div className="mt-1 p-2 bg-emerald-500/20 rounded-full h-fit flex-shrink-0 text-emerald-600 dark:text-emerald-400">
                <TrendingUp className="h-4 w-4" />
              </div>
              <div className="flex-1 space-y-1">
                <div className="flex items-center justify-between">
                  <h4 className="font-semibold text-emerald-900 dark:text-emerald-100 text-sm">{opp.title}</h4>
                  <span className="text-[10px] font-bold text-emerald-600 bg-emerald-500/20 px-2 py-0.5 rounded-full">{opp.confidence}% Match</span>
                </div>
                <p className="text-xs text-foreground/80 leading-relaxed">{opp.description}</p>
                <button className="text-xs text-emerald-600 dark:text-emerald-400 font-bold mt-2 flex items-center gap-1 hover:underline">
                  {opp.action} <ArrowRight className="h-3 w-3" />
                </button>
              </div>
            </CardContent>
          </Card>
        ))}

        {analysis.risks.map((risk, idx) => (
          <Card key={idx} className="border-rose-500/20 bg-rose-500/5 dark:bg-rose-500/10 shadow-sm transition-all hover:shadow-md">
            <CardContent className="p-4 flex gap-4">
              <div className="mt-1 p-2 bg-rose-500/20 rounded-full h-fit flex-shrink-0 text-rose-600 dark:text-rose-400">
                <AlertTriangle className="h-4 w-4" />
              </div>
              <div className="flex-1 space-y-1">
                <div className="flex items-center justify-between">
                  <h4 className="font-semibold text-rose-900 dark:text-rose-100 text-sm">{risk.title}</h4>
                  <span className="text-[10px] font-bold text-rose-600 bg-rose-500/20 px-2 py-0.5 rounded-full">{risk.impact} Impact</span>
                </div>
                <p className="text-xs text-foreground/80 leading-relaxed">{risk.description}</p>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Strategic Recommendations */}
      <Card className="border-muted shadow-sm">
        <CardHeader className="pb-2 pt-4 px-4">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            Strategic Next Steps
          </CardTitle>
        </CardHeader>
        <CardContent className="px-4 pb-4">
          <ul className="space-y-2">
            {analysis.recommendations.map((rec, idx) => (
              <li key={idx} className="text-xs flex items-start gap-2">
                <div className="h-1.5 w-1.5 rounded-full bg-indigo-500 mt-1.5 shrink-0" />
                <span className="text-foreground/80">{rec}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}

function AiLoadingState() {
  return (
    <div className="flex flex-col gap-6 w-full animate-pulse">
      <Card className="border-indigo-500/10 bg-indigo-500/5 p-6 space-y-4">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-3">
             <Skeleton className="h-10 w-10 rounded-lg" />
             <div className="space-y-2">
               <Skeleton className="h-4 w-32" />
               <Skeleton className="h-3 w-24" />
             </div>
          </div>
          <Skeleton className="h-6 w-20 rounded-full" />
        </div>
        <div className="space-y-2 pt-2">
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-[90%]" />
          <Skeleton className="h-3 w-[80%]" />
        </div>
      </Card>
      <div className="space-y-4">
        {[1, 2].map((i) => (
          <Card key={i} className="p-4 flex gap-4">
             <Skeleton className="h-8 w-8 rounded-full" />
             <div className="flex-1 space-y-3 mt-1">
               <Skeleton className="h-3 w-1/3" />
               <Skeleton className="h-3 w-[90%]" />
               <Skeleton className="h-3 w-[60%]" />
             </div>
          </Card>
        ))}
      </div>
    </div>
  )
}
